### ISSUE TITLE
AlphaManager里面的content会有内存泄露情况

### ISSUE THREAD

**Issue by EspoirX** [alibaba/alpha#10]

**Comment by barnett-yuxiang** [comment]
问题都没人回答吗？服务意识有待提高！！！

我解答下吧，AlphaManager是个singleton的设计，context在这套设计中意图是check当前进程（pkgname），因此这里用Application的Context，而不是Activity的context。所以，alpha这里的作法更优的方式是直接用application context。另，使用方也要注意

**Comment by barnett-yuxiang** [comment]
@EspoirX 你可以关掉这个问题了
