### ISSUE TITLE
applicaiton中初始化，怎么等待所有任务都结束？

### ISSUE THREAD

**Issue by mrme2014** [alibaba/alpha#11]
applicaiton中初始化，怎么等待所有任务都结束？

waitUntilFinish该方法会阻塞主线程

**Comment by mrme2014** [comment]
老哥  i need you

**Comment by YummyLau** [comment]
看了下实现，会阻塞。针对alpha做了调整，目前自己项目用了自己实现的了。

**Comment by mrme2014** [comment]
> 看了下实现，会阻塞。针对alpha做了调整，目前自己项目用了自己实现的了。

老哥。咋实现的？可否开源下。加个QQ？863597281

**Comment by YummyLau** [comment]
> > 看了下实现，会阻塞。针对alpha做了调整，目前自己项目用了自己实现的了。
> 
> 老哥。咋实现的？可否开源下。加个QQ？863597281

https://github.com/alibaba/alpha/issues/11#issuecomment-500325440

**Comment by YummyLau** [comment]
> > 看了下实现，会阻塞。针对alpha做了调整，目前自己项目用了自己实现的了。
> 
> 老哥。咋实现的？可否开源下。加个QQ？863597281

https://github.com/YummyLau/Anchors

**Comment by mrme2014** [comment]
> > > 看了下实现，会阻塞。针对alpha做了调整，目前自己项目用了自己实现的了。

```

       Project.Builder builder1 = new Project.Builder(PROJECT_1, testTaskFactory);
        builder1.add(TASK_10);
        builder1.add(TASK_11).dependOn(TASK_10);
        builder1.add(TASK_12).dependOn(TASK_11);
        builder1.add(TASK_13).dependOn(TASK_12);
        Project project1 = builder1.build();

        AnchorsManager.getInstance().debuggable(true)
                .addAnchors(TASK_10)
                .start(project1);
```
问题1：   `start()`方法如果传入的是project对象。那么运行起来会有报空指针,日志如下
```
Attempt to invoke virtual method 'android.util.SparseArray com.effective.android.anchors.TaskRuntimeInfo.getStateTime()' on a null object reference
        at com.effective.android.anchors.LogTaskListener.logTaskRuntimeInfoString(LogTaskListener.java:28)
        at com.effective.android.anchors.LogTaskListener.onFinish(LogTaskListener.java:23)
        at com.effective.android.anchors.Task.toFinish(Task.java:140)
        at com.effective.android.anchors.Task.run(Task.java:101)
```

**Comment by YummyLau** [comment]
> > > > 看了下实现，会阻塞。针对alpha做了调整，目前自己项目用了自己实现的了。
> 
> ```
> 
>        Project.Builder builder1 = new Project.Builder(PROJECT_1, testTaskFactory);
>         builder1.add(TASK_10);
>         builder1.add(TASK_11).dependOn(TASK_10);
>         builder1.add(TASK_12).dependOn(TASK_11);
>         builder1.add(TASK_13).dependOn(TASK_12);
>         Project project1 = builder1.build();
> 
>         AnchorsManager.getInstance().debuggable(true)
>                 .addAnchors(TASK_10)
>                 .start(project1);
> ```
> 
> 问题1： `start()`方法如果传入的是project对象。那么运行起来会有报空指针,日志如下
> 
> ```
> Attempt to invoke virtual method 'android.util.SparseArray com.effective.android.anchors.TaskRuntimeInfo.getStateTime()' on a null object reference
>         at com.effective.android.anchors.LogTaskListener.logTaskRuntimeInfoString(LogTaskListener.java:28)
>         at com.effective.android.anchors.LogTaskListener.onFinish(LogTaskListener.java:23)
>         at com.effective.android.anchors.Task.toFinish(Task.java:140)
>         at com.effective.android.anchors.Task.run(Task.java:101)
> ```

最新版本已经全部支持。

**Comment by parcool** [comment]
关闭这个问题的原因是没使用它了吗？
