### ISSUE TITLE
怎样设置在所有的初始化任务都完成后，再结束Application.onCreate()？

### ISSUE THREAD

**Issue by InnocentYang** [alibaba/alpha#13]
假设我有一个初始化要比较耗时，比如读取一个很大的配置文件，它要耗时2秒，读取文件可以用Task异步执行，
但这个配置文件很重要，项目里到处都要用到，
alpha有没有办法做到，在Application.onCreate()里初始化读取配置文件，此时把主线程挂起，直到任务完成后，再恢复主线程，Application.onCreate()执行完成，继续下一步，进入主页？

如果自己要做这个需求，只能是在Application.onCreate()里直接调用方法，同步执行，
感觉这种操作不适合做异步，
就是想问问，alpha框架有没有办法完成这样的需求。

**Comment by YummyLau** [comment]
[Anchors](https://github.com/YummyLau/Anchors) 你倒是可以考虑下。 @InnocentYang

**Comment by wz147258** [comment]
不用那么麻烦，是阻塞主进程的主线程，直到所有需要的任务结束是吧。
可以再开一个进程做这事，然后主进程的主线程卡死，等待子进程的完成。在子进程中的主线程开一个loading或其他的，然后把任务都放在后台执行，然后完成时子进程写入一个文件表示初始化完成，主进程检测到后才继续执行下去
