### ISSUE TITLE
Failed to resolve: com.alibaba.android:alpha:1.0.0.1

### ISSUE THREAD

**Issue by liuzhao2007** [alibaba/alpha#3]
Failed to resolve: com.alibaba.android:alpha:1.0.0.1

按照配置，显示找不到这个库，9月底就是这个bug，现在11月底。阿里开源的这个项目让人失望

**Comment by simplezhli** [comment]
@liuzhao2007 文档确实有点水，我在提交记录里找到了配置，你可以试试：

```xml
api 'com.alibaba.android:alpha:1.0.0.1'
```

```xml
maven {
      url "https://dl.bintray.com/zhangsl/maven"
}
```

**Comment by liuzhao2007** [comment]
@simplezhli 非常感谢！

**Comment by liushengqiang** [comment]
@simplezhli 
maven {
      url "https://dl.bintray.com/zhangsl/maven"
}
这段代码放哪里？然道是放项目根目录的gradle中？可是那个文件我已经有同样的代码了，修改为这句的话同步时EvenBus会报错。

**Comment by YummyLau** [comment]
@liushengqiang 有多个url分开写就行了。maven支持多个url

repositories {
  maven { url "xxxxx" }
  maven { url "xxxx" }
 ...
}

**Comment by heyangJob** [comment]
> Failed to resolve: com.alibaba.android:alpha:1.0.0.1
> 
> 按照配置，显示找不到这个库，9月底就是这个bug，现在11月底。阿里开源的这个项目让人失望

头条祁同伟哈哈哈
